In [2]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])                      # 1D array (vector)
a2 = np.array([[1, 2, 3], [4, 5, 6]])         # 2D array (matriz)
a3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) # 3D array


In [4]:
print(a2.shape)  # dimensiones (filas, columnas)
print(a2.ndim)   # número de dimensiones
print(a2.dtype)  # tipo de dato (int64, float64, etc.)
print(a2.size)   # número total de elementos
print(type(a2))  # tipo de objeto (numpy.ndarray)


(2, 3)
2
int64
6
<class 'numpy.ndarray'>


In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.randint(10, size=(3,3))

array([[4, 6, 4],
       [0, 3, 7],
       [3, 2, 8]])

In [11]:
np.random.random((3,3))

array([[0.28513999, 0.13547553, 0.34032066],
       [0.0485966 , 0.93257697, 0.67127985],
       [0.3425164 , 0.2698098 , 0.32716794]])

In [12]:
np.random.randint(20, size=(3,3))

array([[16,  0,  1],
       [ 0,  4,  7],
       [19,  8,  6]])

In [13]:
a = np.array([1, 2, 3], dtype=np.int8)
b = np.array([1.2, 3.5, 5.1], dtype=np.float32)
a,b

(array([1, 2, 3], dtype=int8), array([1.2, 3.5, 5.1], dtype=float32))

In [14]:
b.astype(int)
b

array([1.2, 3.5, 5.1], dtype=float32)

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a[0,1])

2


In [16]:
print(a[:, 1])

[2 5]


In [17]:
print(a[0:2, 1:3])

[[2 3]
 [5 6]]


In [18]:
a = np.array([1, 2, 3, 4])
np.cumsum(a)

array([ 1,  3,  6, 10])

In [19]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [20]:
print(a + b)
print(a * b)
print(a / 2)
print(np.square(a))
print(np.log(a))
print(np.exp(a))

[11 22 33]
[10 40 90]
[0.5 1.  1.5]
[1 4 9]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


In [21]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 2, 3])

print(a + b)


[[2 4 6]
 [5 7 9]]


In [22]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(a))          # suma total
print(np.mean(a))         # promedio
print(np.std(a))          # desviación estándar
print(np.var(a))          # varianza
print(np.min(a))          # mínimo
print(np.max(a))          # máximo
print(np.argmin(a))       # índice del valor mínimo
print(np.argmax(a))       # índice del valor máximo


21
3.5
1.707825127659933
2.9166666666666665
1
6
0
5


In [23]:
np.sum(a, axis=0)  # suma por columnas
np.sum(a, axis=1)  # suma por filas


array([ 6, 15])

In [24]:
a = np.array([1, 2, 3, 4])
np.cumsum(a)
# → array([ 1,  3,  6, 10])


array([ 1,  3,  6, 10])

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
a.T

array([0, 1, 2, 3, 4, 5])

In [29]:
arr = np.array([[3, 1, 2],
                [6, 5, 4]])

print(np.sort(arr))           # ordena valores
print(np.argsort(arr))        # índices que ordenarían el array
print(np.argmax(arr, axis=1)) # índice del valor máximo por fila
print(np.argmin(arr, axis=0)) # índice del valor mínimo por columna


[[1 2 3]
 [4 5 6]]
[[1 2 0]
 [2 1 0]]
[0 0]
[0 0 0]


In [32]:
data = np.random.randn(1000)
print(np.mean(data))
print(np.median(data))
print(np.percentile(data, 90))

-0.035601386114436195
0.04876966082478217
1.1689732868156775
